export const RUN_SEQUENCE = 'RUN_SEQUENCE';

export const CITY_SELECT = 'CITY_SELECT';
export const VIEW_SELECT = 'VIEW_SELECT';

export const SIXTEEN_DATA_REQUEST = 'SIXTEEN_DATA_REQUEST';
export const SIXTEEN_DATA_FAILURE = 'SIXTEEN_DATA_FAILURE';
export const SIXTEEN_DATA_RESPONSE = 'SIXTEEN_DATA_RESPONSE';

export const SIXTEEN_DATA_TRIPLET = [
    SIXTEEN_DATA_REQUEST,
    SIXTEEN_DATA_RESPONSE,
    SIXTEEN_DATA_FAILURE,
];